/* DO NOT EDIT, file generated by nestjs-i18n */
  
/* eslint-disable */
/* prettier-ignore */
import { Path } from "nestjs-i18n";
/* prettier-ignore */
export type I18nTranslations = {
    "error_messages": {
        "ok": string;
        "product": {
            "creating": string;
            "updating": string;
            "deleting": string;
            "publishing": string;
            "not_found": string;
            "invalid_type": string;
            "duplicated_sku": string;
        };
        "product_line": {
            "creating": string;
            "updating": string;
            "deleting": string;
        };
        "product_collection": {
            "creating": string;
            "updating": string;
            "deleting": string;
        };
        "retail_store": {
            "creating": string;
            "updating": string;
            "deleting": string;
        };
        "user": {
            "registering": string;
            "conflict": string;
            "not_found": string;
            "invalid_id": string;
        };
        "user_token": {
            "not_found": string;
            "unsable_token": string;
        };
        "auth": {
            "refresing_token": string;
            "revoking_token": string;
            "incorrect_password": string;
        };
        "discount": {
            "creating": string;
            "updating": string;
            "deleting": string;
            "existed": string;
            "not_found": string;
        };
        "inventory": {
            "creating": string;
            "updating": string;
            "product_not_found": string;
        };
        "shopping_cart": {
            "out_of_order": string;
            "not_found": string;
        };
    };
    "success_messages": {
        "ok": string;
        "product": {
            "created": string;
            "updated": string;
            "deleted": string;
            "published": string;
        };
        "product_line": {
            "created": string;
            "updated": string;
            "deleted": string;
        };
        "product_collection": {
            "created": string;
            "updated": string;
            "deleted": string;
        };
        "retail_store": {
            "creating": string;
            "updating": string;
            "deleting": string;
            "created": string;
            "updated": string;
            "deleted": string;
        };
        "user": {
            "registered": string;
            "created": string;
        };
        "user_token": {};
        "auth": {
            "logged_in": string;
            "logged_out": string;
            "refreshed_token": string;
            "reset_password": string;
        };
        "discount": {
            "created": string;
            "updated": string;
            "deleted": string;
        };
        "shopping_cart": {
            "added": string;
            "updated": string;
        };
        "inventory": {
            "created": string;
        };
    };
};
/* prettier-ignore */
export type I18nPath = Path<I18nTranslations>;
