export enum Respositories {
	USER = 'USER_REPOSITORY',
	USER_TOKEN = 'USER_TOKEN_REPOSITORY',
	PRODUCT = 'BASE_PRODUCT_REPOSITORY',
	SNEAKER_PRODUCT = 'SNEAKER_PRODUCT_REPOSITORY',
	TOP_HALF_PRODUCT = 'TOP_HALF_PRODUCT_REPOSITORY',
	ACCESSORY_PRODUCT = 'ACCESSORY_PRODUCT_REPOSITORY',
	PRODUCT_COLLECTION = 'PRODUCT_COLLECTION_REPOSITORY',
	PRODUCT_LINE = 'PRODUCT_LINE_REPOSITORY',
	BRANCH_STORE = 'BRANCH_STORE_REPOSITORY',
	INVENTORY = 'INVENTORY_REPOSITORY',
	DISCOUNT = 'DISCOUNT_REPOSITORY',
	USER_CART = 'USER_CART',
	ORDER = 'ORDER'
}
