enum Providers {
	USER_REPOSITORY = 'USER_REPOSITORY',
	USER_TOKEN_REPOSITORY = 'USER_TOKEN_REPOSITORY',
	PRODUCT_REPOSITORY = 'BASE_PRODUCT_REPOSITORY',
	SNEAKER_PRODUCT_REPOSITORY = 'SNEAKER_PRODUCT_REPOSITORY',
	PRODUCT_COLLECTION_REPOSITORY = 'PRODUCT_COLLECTION_REPOSITORY',
	PRODUCT_LINE_REPOSITORY = 'PRODUCT_LINE_REPOSITORY'
}

export default Providers
